apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../test

namePrefix: instancetemplate-

commonLabels:
  cluster-name: instancetemplate
  app.kubernetes.io/instance: instancetemplate

patchesStrategicMerge:
  - |-
    kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: postgres-patroni
    spec:
      volumeClaimTemplates:
      - kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: postgres-patroni
        spec:
          storageClassName: rook-ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          volumeMode: Filesystem

secretGenerator:
  - name: postgres-patroni
    envs:
    - passwords.env
  - name: postgres
    envs:
    - postgres.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: quay.io/pflaeging/postgres-patroni:latest
    newName: image-registry.openshift-image-registry.svc:5000/demo-fh/postgres-patroni
    newTag: "0.5"