kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-patroni
subjects:
  - kind: ServiceAccount
    name: postgres-patroni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-patroni
