kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-patroni
rules:
  - verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - endpoints
  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - pods
