kind: Service
apiVersion: v1
metadata:
  name: postgres-patroni-replica
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    application: postgres-patroni
    role: replica
  type: ClusterIP
  sessionAffinity: None
